### ISSUE TITLE
will this work with npm workspaces?

### ISSUE THREAD

**Issue by katlim-br** [Butterwire/serverless-plugin-monorepo#35]
Hi

I know the docs say yarn workspace, but since yw and npm workspaces rely on the same mechanism (symlinks), will it work with the latter?.

I like better npm workspaces because it doesn't allow you to add a dependency on the child projects, thus avoiding versions mismatch

Thanks

**Comment by katlim-br** [comment]
I tried this npm workspaces and it did not work. for anyone needing this info.

**Comment by drewloomer** [comment]
Hacky way to make `serverless deploy` work inside of an NPM Workspace:

```yml
plugins:
  - serverless-plugin-scripts

custom:
  scripts:
    hooks:
      # node_modules needs to be in this directory, but NPM workspaces don't work that way
      'package:initialize': ln -s ../../node_modules
      'package:finalize': rm node_modules
```
